### ISSUE TITLE
having problems setting up a typescript class

### ISSUE THREAD

**Issue by TENDesign** [sbruno81/rets-client#103]
I am working on a retriever. To be honest this is really my first venture into nodejs. I am using typescript and transpiling to native. I am getting this error when I run my script:

```
TypeError: Cannot read property 'getAutoLogoutClient' of undefined
    at new retsAuth (/mnt/c/Development/activemls/dist/retriever/auth.js:8:28)
    at Object.<anonymous> (/mnt/c/Development/activemls/dist/index.js:5:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

and so my script is built like this. I first have a file containing the login credentials for 1 mls...

```
export const auth = {
    loginUrl: 'myloginurl',
    username: 'username',
    password: 'password',
    version: 'RETS/1.7.2',
}
```

then my retriever class:

```
import { rets } from 'rets-client';

export class retsAuth {

    constructor(
        private auth: any,
    ) {

        console.log(auth);
        rets.getAutoLogoutClient(auth, (client) => {

        });
    }

}
```

and then lastly i call the class in my index.ts

```
import { auth } from './norris/auth';
import { retsAuth } from './retriever/auth';

new retsAuth(auth);
```

i thought this seemed pretty straight forward, but am I missing something?

**Comment by zacronos** [comment]
In your retriever class, try using `import * as rets from 'rets-client';` -- let me know if that does what you want.

**Comment by TENDesign** [comment]
yep!

```
import * as rets from 'rets-client';

export class retsAuth {

    constructor(
        private auth: any,
    ) {

        rets.getAutoLogoutClient(auth, (client) => {
            return client.metadata.getResources()
            .then((data) => {
                console.log(data)
            })
        });
    }

}
```
then my response was:
```
{ results: [ { info: [Object], metadata: [Array] } ],
  type: 'METADATA-RESOURCE',
  headerInfo:
   { cacheControl: 'no-cache',
     contentType: 'text/xml; charset=utf-8',
     date: 'Tue, 30 Jan 2018 03:50:53 GMT',
     expires: '-1',
     pragma: 'no-cache',
     retsVersion: 'RETS/1.7.2',
     server: 'Microsoft-IIS/8.0',
     xAspNetVersion: '4.0.30319',
     xPoweredBy: 'ASP.NET',
     contentLength: '3107',
     xCache: 'MISS from localhost',
     xCacheLookup: 'MISS from localhost:3028',
     via: '1.0 localhost (squid/3.1.20)',
     connection: 'close' },
  replyCode: '0',
  replyTag: 'OPERATION_SUCCESSFUL',
  replyText: 'Operation Success.',
  entriesReceived: 1 }
```
So I would have thats exactly what was expected. I assume I should now be able to access all the available methods as excpected in the docs!
