### ISSUE TITLE
Getting 400 error on login

### ISSUE THREAD

**Issue by hamedmam** [sbruno81/rets-client#110]
Hi,

Thanks for such a great work.
I am trying to use rets-client to login and I have copied and pasted your example without no changes except for retsLoginUrl, retsUser, and retsPassword
and that is the complete error using DEBUG

> rets-client:request request: { debugId: 1,
  uri: 'http://rets.torontomls.net:6103/rets-treb3pv/server/login',
  method: 'GET',
  headers:
   { 'User-Agent': 'RETS node-client/4.x',
     'RETS-Version': 'RETS/1.7.2',
     'RETS-UA-Authorization': 'Digest xxxxxxxxxxxxxxxxx',
     host: 'rets.torontomls.net:6103' } } +10ms
  rets-client:request response: { debugId: 1,
  headers:
   { server: 'Apache-Coyote/1.1',
     'rets-version': 'RETS/1.7',
     'content-type': 'text/plain;charset=ISO-8859-1',
     'transfer-encoding': 'chunked',
     date: 'Sun, 08 Apr 2018 05:30:30 GMT',
     connection: 'close' },
  statusCode: 400,
  body: '<RETS ReplyCode="20036" ReplyText="Missing or Invalid RETS Version" >\n</RETS>\r\n' } +126ms
  rets-client:main RETS login error: RETS Server error while attempting login - HTTP Status 400 returned (Bad Request) +2ms
   ERROR: issue encountered:
      httpStatus: 400
      httpStatusMessage: "Bad Request"
      name: "RetsServerError"
      retsMethod: "login"
      queryOptions: {}
      headerInfo: undefined
      message: "RETS Server error while attempting login - HTTP Status 400 returned (Bad Request)"

   RetsServerError: RETS Server error while attempting login - HTTP Status 400 returned (Bad Request)
       at /Users/x205096/Desktop/hamed/server/node_modules/rets-client/dist/utils/retsHttp.js:39:17
       at tryCatcher (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
       at Promise._settlePromiseFromHandler (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:508:31)
       at Promise._settlePromiseAt (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:584:18)
       at Promise._settlePromises (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:700:14)
       at Async._drainQueue (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/async.js:123:16)
       at Async._drainQueues (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues (/Users/x205096/Desktop/hamed/server/node_modules/rets-client/node_modules/bluebird/js/main/async.js:15:14)
       at runCallback (timers.js:789:20)
       at tryOnImmediate (timers.js:751:5)
       at processImmediate [as _immediateCallback] (timers.js:722:5)

Any clue why is it happening?

**Comment by hamedmam** [comment]
@esvinson can you help me please ?

**Comment by esvinson** [comment]
Try setting the version option to RETS/1.7  instead of RETS/1.7.2  trying the URL directly wouldn't give me the auth popup unless the version was 1.7.

`{version: 'RETS/1.7'}`

**Comment by hamedmam** [comment]
Thanks a lot. That solved it. Way to go guys

**Comment by MustafaSohail1** [comment]
@hamedmam Hey bro, I also want to access the data of TREB real estate listings into my website. 
Can you help me in this matter? if yes than please contact me through my email.
**Email: mushiindus@gmail.com**
