### ISSUE TITLE
Buffer.write(string, encoding, offset[, length]) is no longer supported

### ISSUE THREAD

**Issue by svenvarkel** [sbruno81/rets-client#115]
It seems that some component that rets-client uses is still using deprecated and outphased NodeJS calls.

This error occurs when I try to pull media from a RETS server:

```
{ RetsProcessingError: Error while processing RETS response for getObject - Buffer.write(string, encoding, offset[, length]) is no longer supported
    at Object.ensureRetsError (/sandbox/retsclient/node_modules/rets-client/dist/utils/errors.js:133:14)
    at onError (/sandbox/retsclient/node_modules/rets-client/dist/clientModules/object.stream.js:38:30)
    at /sandbox/retsclient/node_modules/rets-client/dist/clientModules/object.stream.js:56:18
    at tryCatcher (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/sandbox/retsclient/node_modules/rets-client/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by svenvarkel** [comment]
It can be fixed by upgrading formidable dependency

**Comment by apocist** [comment]
Ran into the same issue, looks to now be fixed with #112
