### ISSUE TITLE
getPhotos returning error

### ISSUE THREAD

**Issue by geoffmc** [sbruno81/rets-client#14]
Hi,

The latest version built on promises is awesome! I'm having trouble with getPhotos and can't figure out why. I think it's related to the @retsSession in object.coffee but I've been trying to figure it out forever and haven't gotten anywhere. I don't think it's a problem on the server because I can do other operations (such as getting metadata or listings) and it used to work in the older version.

Here is what I'm trying to run (where getAutoLogoutClient works properly and the listing key in getPhotos does exist on the server):
```
rets.getAutoLogoutClient(clientSettings, function(client) {
  return client.objects.getPhotos("Property", "ThumbnailPhoto", "11937301");
}).then(function(result) {
  console.log("Done");
});
```

Here is the error I'm getting:
```
ERROR: issue encountered: TypeError: undefined is not a function
  at /Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/lib/clientModules/object.coffee:46:9
  at tryCatcher (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:70:37)
  at Object.getObject (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/lib/clientModules/object.coffee:44:7)
  at Object.getPhotos (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/lib/clientModules/object.coffee:73:4)
  at /Users/themcgills/nodejs/rets-deb-sync/testPull.js:216:25
  at /Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/lib/client.coffee:87:7
  at tryCatcher (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
  at Function.Promise.attempt.Promise.try (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/method.js:31:24)
  at /Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/lib/client.coffee:86:5
  at tryCatcher (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/themcgills/nodejs/rets-deb-sync/node_modules/rets-client/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:367:17)
```

If I go into object.coffee and try logging the req variable declared on line 37 then this is what I get:
```
test _bitField=0, _fulfillmentHandler0=undefined, _rejectionHandler0=undefined, _progressHandler0=undefined, _promise0=undefined, _receiver
0=undefined, _settledValue=undefined
```

Any help would be greatly appreciated!!

**Comment by zacronos** [comment]
Hi @geoffmc, thanks for the report.  That section is the area of the module I've looked at and used the least, so if it used to work in the older version, then it sounds pretty likely you have indeed found a bug.  I'll take a look and see what I can find.

**Comment by zacronos** [comment]
Hey @geoffmc, I think I've fixed the problem.

I found a couple minor bugs in `object.coffee`, gave it some better error handling, and added the full http response object to the object that resolves from the `getObject()` call -- I've released those changes as v3.1.0 since that's a small feature addition to `getObject()`.

Give it a try and let me know if it works for you now.

**Comment by geoffmc** [comment]
It's working great now! Thanks for fixing this so quickly @zacronos

**Comment by zacronos** [comment]
no problem, thanks for the detailed report
