### ISSUE TITLE
TypeError: Cannot read property 'RETS' of undefined

### ISSUE THREAD

**Issue by avtaniket** [sbruno81/rets-client#21]
Hi, I have come across issue, when connection to MLS server to fetch property data.

/home/node_modules/rets-client/lib/utils.js:8
    var replyCode = result.RETS.$.ReplyCode;
                          ^
TypeError: Cannot read property 'RETS' of undefined
    at Object.replyCodeCheck (/home/node_modules/rets-client/lib/utils.js:8:27)
    at /home/node_modules/rets-client/lib/search.js:25:20
    at Parser.<anonymous> (/home/node_modules/xml2js/lib/xml2js.js:488:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/home/node_modules/xml2js/lib/xml2js.js:507:16)
    at Parser.parseString (/home/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/home/node_modules/xml2js/lib/xml2js.js:535:19)
    at parseCompactDecoded (/home/node_modules/rets-client/lib/search.js:23:5)
    at /home/node_modules/rets-client/lib/search.js:286:9

**Comment by zacronos** [comment]
Hi @avtaniket, based on the stacktrace, it looks like you are using v1.x of rets-client.  latest/master is v4.x, which is a pretty thorough rewrite including more consistent error handling, so I would suggest changing your code to use that version.  If you still have problems when using 4.x, I'll dig into it.

If you really want to stick with v1.x, @sbruno81 might be able to help you as he maintains that branch.

**Comment by avtaniket** [comment]
@zacronos as suggested, I updated to latest version, but still getting same issue sometimes.

`TypeError: Cannot read property 'RETS' of undefined
    at Object.replyCodeCheck (/opt/node_modules/rets-client/lib/utils.js:8:27)
    at /opt/node_modules/rets-client/lib/search.js:25:20
    at Parser.<anonymous> (/opt/node_modules/xml2js/lib/xml2js.js:488:18)
    at Parser.emit (events.js:95:17)
    at Parser.exports.Parser.Parser.parseString (/opt/node_modules/xml2js/lib/xml2js.js:507:16)
    at Parser.parseString (/opt/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/opt/node_modules/xml2js/lib/xml2js.js:535:19)
    at parseCompactDecoded (/opt/node_modules/rets-client/lib/search.js:23:5)
    at /opt/node_modules/rets-client/lib/search.js:286:9
    at Request._callback (/opt/node_modules/rets-client/lib/search.js:148:17)`

Im using node v4, ubuntu 64

Let me know if you need additional information to look into this issue.

Thanks again for your support.

**Comment by zacronos** [comment]
Please double-check that you are using rets-client v4.x.  (You will probably have to change your code to use 4.x properly, as it has a very different API than 1.x does.)

The stack trace you are giving is impossible with the 4.x version.  There is no `replyCodeCheck` function, and there isn't even a `utils.js` file -- the code has been almost completely rewritten between 1.x and 4.x.

**Comment by avtaniket** [comment]
@zacronos Update the script with version 4.1.4 and have below error which occurs sometimes

`Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (MEAN/properties/node_modules/rets-client/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (MEAN/properties/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:469:22)
    at MEAN/properties/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:486:17
    at onError (MEAN/properties/node_modules/rets-client/dist/clientModules/object.stream.js:38:18)
    at null.<anonymous> (MEAN/properties/node_modules/rets-client/dist/utils/retsParsing.js:48:16)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at Parser.parse (MEAN/properties/node_modules/rets-client/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (MEAN/properties/node_modules/rets-client/node_modules/node-expat/lib/node-expat.js:60:19)
    at DestroyableTransform.ondata (MEAN/properties/node_modules/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at readableAddChunk (MEAN/properties/node_modules/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (MEAN/properties/node_modules/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at DestroyableTransform.Transform.push (MEAN/properties/node_modules/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at afterTransform (MEAN/properties/node_modules/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:51)`

Thanks for amazing package!
