### ISSUE TITLE
RETS Server replied with an error code - ReplyCode 20200 (UNKNOWN_QUERY_FIELD)

### ISSUE THREAD

**Issue by nohona** [sbruno81/rets-client#29]
Not sure if I am using the proper field, RETS was just updated with new fields. (ActiveYN does not exist). I apologize, for not being more informed. 

```javascript
return client.search.query("OpenHouse", "OpenHouse", "(OpenHouseType=PUB),(StandardStatus=A)", {limit:100, offset:10})
```

Tried non-stream example code with following result:

```bash
/usr/local/bin/node app.js
===================================
========  System Metadata  ========
===================================
    retsVersion: RETS/1.7.2
    retsServer: Apache-Coyote/1.1
    MemberName: XXXX
    User: XXX
    Broker:
    MetadataVersion: 1.00.00018
    MetadataTimestamp: 2016-03-22T09:18:33
    MinMetadataTimestamp: 2016-03-22T09:18:33
    TimeoutSeconds: 1800000
    Action: /contact/rets/action
    GetMetadata: /contact/rets/getMetadata
    GetObject: /contact/rets/getObject
    Login: /contact/rets/login
    Logout: /contact/rets/logout
    X-PostObject: /contact/rets/postObject
    Search: /contact/rets/search
    X-Selector: /contact/rets/selector
    Update: /contact/rets/update

======================================
========  Resources Metadata  ========
======================================
    Date: 2016-03-22T09:18:33
    Version: 1.00.00015
    rowsReceived: 3

-------- Resource 0 --------
    ResourceID: OpenHouse
    StandardName: 
    VisibleName: OpenHouse
    ObjectVersion: 1.00.00000

-------- Resource 1 --------
    ResourceID: Property
    StandardName: 
    VisibleName: Property
    ObjectVersion: 1.00.00000

-------- Resource 2 --------
    ResourceID: Media
    StandardName: 
    VisibleName: Media
    ObjectVersion: 

===========================================================
========  Class Metadata (from Property Resource)  ========
===========================================================
    Resource: Property
    Date: 2016-03-22T09:18:33
    Version: 1.00.00007
    rowsReceived: 7

-------- Table 0 --------
    ClassName: Residential
    StandardName: 
    VisibleName: Residential
    TableVersion: 1.00.00005

-------- Table 1 --------
    ClassName: Commercial
    StandardName: 
    VisibleName: Commercial
    TableVersion: 1.00.00007

-------- Table 2 --------
    ClassName: Land
    StandardName: 
    VisibleName: Land
    TableVersion: 1.00.00005

-------- Table 3 --------
    ClassName: Mobile
    StandardName: 
    VisibleName: Mobile
    TableVersion: 1.00.00005

-------- Table 4 --------
    ClassName: CrossProperty
    StandardName: 
    VisibleName: CrossProperty
    TableVersion: 1.00.00005

-------- Table 5 --------
    ClassName: ResidentialIncome
    StandardName: 
    VisibleName: ResidentialIncome
    TableVersion: 1.00.00005

-------- Table 6 --------
    ClassName: ResidentialLease
    StandardName: 
    VisibleName: ResidentialLease
    TableVersion: 1.00.00005

=============================================
========  OpenHouse Table Metadata  ========
=============================================
    Class: OpenHouse
    Resource: OpenHouse
    Date: 2015-03-11T12:37:12
    Version: 1.00.00004
    rowsReceived: 28

-------- Field 0 --------
    MetadataEntryID: InputEntryOrder
    SystemName: InputEntryOrder
    ShortName: InputEntryOrder
    LongName: InputEntryOrder
    DataType: Int

-------- Field 1 --------
    MetadataEntryID: showingofficeid
    SystemName: showingofficeid
    ShortName: showingofficeid
    LongName: showingofficeid
    DataType: Character

-------- Field 2 --------
    MetadataEntryID: ShowingContactName
    SystemName: ShowingContactName
    ShortName: ShowingContactName
    LongName: ShowingContactName
    DataType: Character

-------- Field 3 --------
    MetadataEntryID: ClassID
    SystemName: ClassID
    ShortName: ClassID
    LongName: ClassID
    DataType: Int

-------- Field 4 --------
    MetadataEntryID: directions
    SystemName: directions
    ShortName: directions
    LongName: directions
    DataType: Character

-------- Field 5 --------
    MetadataEntryID: ShowingAgentFirstName
    SystemName: ShowingAgentFirstName
    ShortName: ShowingAgentFirstName
    LongName: ShowingAgentFirstName
    DataType: Character

-------- Field 6 --------
    MetadataEntryID: isdeleted
    SystemName: isdeleted
    ShortName: isdeleted
    LongName: isdeleted
    DataType: Boolean

-------- Field 7 --------
    MetadataEntryID: fromdate
    SystemName: fromdate
    ShortName: fromdate
    LongName: fromdate
    DataType: DateTime

-------- Field 8 --------
    MetadataEntryID: fromtime
    SystemName: fromtime
    ShortName: fromtime
    LongName: fromtime
    DataType: Int

-------- Field 9 --------
    MetadataEntryID: ShowingAgentLastName
    SystemName: ShowingAgentLastName
    ShortName: ShowingAgentLastName
    LongName: ShowingAgentLastName
    DataType: Character

-------- Field 10 --------
    MetadataEntryID: ListingKey
    SystemName: ListingKey
    ShortName: ListingKey
    LongName: ListingKey
    DataType: Int

-------- Field 11 --------
    MetadataEntryID: ShowingContactPhoneExt
    SystemName: ShowingContactPhoneExt
    ShortName: ShowingContactPhoneExt
    LongName: ShowingContactPhoneExt
    DataType: Character

-------- Field 12 --------
    MetadataEntryID: ShowingContactType
    SystemName: ShowingContactType
    ShortName: ShowingContactType
    LongName: ShowingContactType
    DataType: Character

-------- Field 13 --------
    MetadataEntryID: ShowingContactPhone
    SystemName: ShowingContactPhone
    ShortName: ShowingContactPhone
    LongName: ShowingContactPhone
    DataType: Character

-------- Field 14 --------
    MetadataEntryID: Refreshments
    SystemName: Refreshments
    ShortName: Refreshments
    LongName: Refreshments
    DataType: Character

-------- Field 15 --------
    MetadataEntryID: MLNumber
    SystemName: MLNumber
    ShortName: MLNumber
    LongName: MLNumber
    DataType: Character

-------- Field 16 --------
    MetadataEntryID: showingagentpublicid
    SystemName: showingagentpublicid
    ShortName: showingagentpublicid
    LongName: showingagentpublicid
    DataType: Character

-------- Field 17 --------
    MetadataEntryID: ShowingAgentStateLicenseNumber
    SystemName: ShowingAgentStateLicenseNumber
    ShortName: ShowingAgentStateLicenseNumber
    LongName: ShowingAgentStateLicenseNumber
    DataType: Character

-------- Field 18 --------
    MetadataEntryID: MLSID
    SystemName: MLSID
    ShortName: MLSID
    LongName: MLSID
    DataType: Character

-------- Field 19 --------
    MetadataEntryID: OpenHouseKey
    SystemName: OpenHouseKey
    ShortName: OpenHouseKey
    LongName: OpenHouseKey
    DataType: Int

-------- Field 20 --------
    MetadataEntryID: OpenHouseType
    SystemName: OpenHouseType
    ShortName: OpenHouseType
    LongName: OpenHouseType
    DataType: Character

-------- Field 21 --------
    MetadataEntryID: hasdrawing
    SystemName: hasdrawing
    ShortName: hasdrawing
    LongName: hasdrawing
    DataType: Boolean

-------- Field 22 --------
    MetadataEntryID: totime
    SystemName: totime
    ShortName: totime
    LongName: totime
    DataType: Int

-------- Field 23 --------
    MetadataEntryID: showingassoc
    SystemName: showingassoc
    ShortName: showingassoc
    LongName: showingassoc
    DataType: Character

-------- Field 24 --------
    MetadataEntryID: OpenHouseAttendance
    SystemName: OpenHouseAttendance
    ShortName: OpenHouseAttendance
    LongName: OpenHouseAttendance
    DataType: Character

-------- Field 25 --------
    MetadataEntryID: SourceDateModified
    SystemName: SourceDateModified
    ShortName: SourceDateModified
    LongName: SourceDateModified
    DataType: DateTime

-------- Field 26 --------
    MetadataEntryID: comments
    SystemName: comments
    ShortName: comments
    LongName: comments
    DataType: Character

-------- Field 27 --------
    MetadataEntryID: OpenHouseID
    SystemName: OpenHouseID
    ShortName: OpenHouseID
    LongName: OpenHouseID
    DataType: Character

ERROR: issue encountered: RetsReplyError: RETS Server replied with an error code - ReplyCode 20200 (UNKNOWN_QUERY_FIELD); ReplyText: Could not parse DMQL2 Query: Unknown field in query at or near position 21. [...ype=PUB),( !-->StandardSta]
    at processStatus (/Users/xxx/WebstormProjects/api_rets_client/node_modules/rets-client/dist/utils/retsParsing.js:113:21)
    at null.<anonymous> (/Users/xxx/WebstormProjects/api_rets_client/node_modules/rets-client/dist/utils/retsParsing.js:126:7)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Parser.parse (/Users/xxx/WebstormProjects/api_rets_client/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/Users/xxx/WebstormProjects/api_rets_client/node_modules/node-expat/lib/node-expat.js:60:19)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/mwitt/WebstormProjects/api_rets_client/node_modules/request/request.js:960:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:743:26)
    at resume_ (_stream_readable.js:723:3)

Process finished with exit code 0
```

**Comment by zacronos** [comment]
Hi @nohona .  Unfortunately, each RETS server can have its own data schema, so the fields available on one server are not necessarily available on another, and there is no way to make a one-size-fits-all example.  You can look at the examples to see a little bit of what you could be doing and how, but that's as much as they will do for you.  Since ActiveYN doesn't exist for you, you'll either need to take that part out of the example or change it to a field that does exist.  There isn't a right answer, it's just a matter of what you're trying to accomplish.

**Comment by nohona** [comment]
Hi Joe,

Thanks for addressing my issue. I did try several combination, but wasn't
able to get any data returned. I guess, I have to dig in deeper and
aproach it differently. I am currently using the RetsConnector pushing the
plain CSV output into a mongo database. My original goal is to create
a REST API. Also, I am hoping the local MLS will make the new Web API
available soon.

Thanks again,
Michael Witt

**Comment by zacronos** [comment]
Gotcha.  Let me know if you have any other questions.
