### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by avtaniket** [sbruno81/rets-client#30]
Hi, I have come across issue, when connection to MLS server to fetch property data.

Using node v4, rest-client latest v4, please let me know if your need additional info to look into this issue.

`TypeError: Cannot read property '0' of undefined
    at /opt/nurealtor-services/node_modules/rets-client/lib/auth.js:45:34
    at Parser.<anonymous> (/opt/nurealtor-services/node_modules/xml2js/lib/xml2js.js:484:18)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/opt/nurealtor-services/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/opt/nurealtor-services/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/opt/nurealtor-services/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/opt/nurealtor-services/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/opt/nurealtor-services/node_modules/sax/lib/sax.js:1301:13)
    at Parser.exports.Parser.Parser.parseString (/opt/nurealtor-services/node_modules/xml2js/lib/xml2js.js:503:31)
    at Parser.parseString (/opt/nurealtor-services/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/opt/nurealtor-services/node_modules/xml2js/lib/xml2js.js:535:19)`

Thank you

**Comment by avtaniket** [comment]
@sbruno81 Can you please assist to fixed above issue, we are using v1.2

**Comment by sbruno81** [comment]
Hi Aniket,

I tried running some tests with node v4 and could not replicate your issue.

What version of RETS is your target server running?


-Steve

On Tue, Apr 12, 2016 at 2:34 AM, aniket takarkhede <notifications@github.com

**Comment by avtaniket** [comment]
For your kind info we are using,

RETS version: RETS/1.7.2

**Comment by mastreips** [comment]
same problem node v.6.3.1

**Comment by zacronos** [comment]
@mastreips: what version of rets-client are you using?

**Comment by mastreips** [comment]
RETS 1.7.2

**Comment by zacronos** [comment]
@mastreips: can you please create a separate ticket for this issue and provide an example of your code that causes the issue?

The original issue raised here was with rets-client v1.2, and the `Cannot read property '<something>' of undefined` error message is a generic javascript error message, so they are probably unrelated.  Thanks!
