### ISSUE TITLE
Unexpected end of xml stream.

### ISSUE THREAD

**Issue by zzeng4** [sbruno81/rets-client#35]
ERROR: issue encountered: RetsProcessingError: Error while processing RETS response for search - Unexpected end of xml stream.
    at null.<anonymous> (/Users/Ubene/Documents/rets/node_modules/rets-client/dist/utils/retsParsing.js:209:19)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at Parser.end (/Users/Ubene/Documents/rets/node_modules/rets-client/node_modules/node-expat/lib/node-expat.js:86:10)
    at Request.onend (stream.js:59:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/Ubene/Documents/rets/node_modules/rets-client/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

Anyone knows why this is happening???

**Comment by zacronos** [comment]
I just made some changes to error handling, so it's possible I introduced a bug.  Do you still get an error if you use version 4.1.x instead of 4.2.0?  (It wouldn't be the same error, because `RetsProcessingError` didn't exist prior to 4.2.0)

**Comment by zzeng4** [comment]
I haven't try yet, but I guess this is because the incompatibility of versions. As the remote server is running at RETS v1.7, not even v.1.72, so it probably is the issue of the server side. Is there anyone else that met the same error like it before?
