### ISSUE TITLE
RetsProcessingError: Error while processing RETS response for getObject - Unexpected end of data: MultipartParser.end(): stream ended unexpectedly: state = START

### ISSUE THREAD

**Issue by li-cn** [sbruno81/rets-client#42]
Sometimes, I get the following error on getObject requests: `RetsProcessingError: Error while processing RETS response for getObject - Unexpected end of data: MultipartParser.end(): stream ended unexpectedly: state = START`

This issue seems to occur infrequently, once in every few thousand getObjects requests. My server will successfully download photos for hundreds of listings using the `client.objects.stream.getObjects` method, and then suddenly crash on this error.

The only thing that I've found to reliably cause the error is commenting out the `parser.write` line from the `interceptor` function in `utils/multipart.js` to simulate no data being written to the multipart parser:

```
  interceptor = (chunk, encoding, callback) ->
    // parser.write(chunk)
    callback()
```

I'm still trying to figure out what response data causes the issue, but it takes many hours of testing on live data to get the error to recur even once.

Has anyone else encountered this issue? @zacronos Would you have any insight into this issue?

Thanks in advance!

---

Relevant error output:

```
{ RetsProcessingError: Error while processing RETS response for getObject - Unexpected end of data: MultipartParser.end(): stream ended unexpectedly: state = START
    at DestroyableTransform.flush [as _flush] (/Users/leonli/Documents/repos/temp/rets-client/dist/utils/multipart.js:142:23)
    at DestroyableTransform.<anonymous> (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
    at endWritable (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DestroyableTransform.onend (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at endReadableNT (/Users/leonli/Documents/repos/temp/rets-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:865:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  retsMethod: 'getObject',
  sourceError: 'Unexpected end of data: MultipartParser.end(): stream ended unexpectedly: state = START',
  name: 'RetsProcessingError',
  message: 'Error while processing RETS response for getObject - Unexpected end of data: MultipartParser.end(): stream ended unexpectedly: state = START',
  headerInfo: 
   { cacheControl: 'private',
     contentLength: '374116',
     contentType: 'multipart/parallel; boundary=creaboundary',
     server: 'Microsoft-IIS/7.5',
     retsVersion: 'RETS/1.7.2',
     retsRequestId: '',
     objectId: '1,2,3,4,5,6,7,8',
     mimeVersion: '1.0',
     xAspNetVersion: '4.0.30319',
     xPoweredBy: 'ASP.NET',
     serverId: '03',
     date: 'Mon, 27 Jun 2016 16:48:01 GMT',
     connection: 'close' } }
```

**Comment by zacronos** [comment]
Sorry, I don't have any insight into what is happening here.  Knowing if certain response data reliably leads to the problem would certainly be very good to know.

It is possible this error could be the correct behavior (e.g. if the RETS server is sending incomplete image data or closing the connection early).  Whether a transient data error like that is the problem or not, it might fix things for you to catch the error on your end and simply retry the request.  It could be simpler to do that then track down an unreliable error.

**Comment by zacronos** [comment]
I've now seen a similar but not identical error and I think I have a solution -- once I've seen the issue replicate itself so I can verify the fix, I'll update master.

**Comment by zacronos** [comment]
I haven't seen the issue again, but I've merged the fix anyway.  Hopefully the error can be caught and handled better now.
