### ISSUE TITLE
ERROR: issue encountered: TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by mastreips** [sbruno81/rets-client#61]
I get the error below when running on rets-client 4.6.0, node v.6.3.1, RETS 1.7.2:
==============================================
========  Residential Table Metadata  ========
===============================================
ERROR: issue encountered: TypeError: Cannot read property 'info' of undefined
    at /home/bitnami/node_modules/rets-client/dist/simple_client.js:84:37
    at tryCatcher (/home/bitnami/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/bitnami/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/bitnami/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/bitnami/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/bitnami/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/bitnami/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)

I used the sample simple client code from the project in the README.md file

**Comment by GifCo** [comment]
Did you also include the Output Helper function right above the client code? 
Also different RETS have different Class and Property types. I know I had issues when I was first testing this module out.
