### ISSUE TITLE
Unhandled exception for autoLogoutClient method with bad server address or no internet connection

### ISSUE THREAD

**Issue by jayrosen1576** [sbruno81/rets-client#67]
In doing some use case testing, I am getting an unhandled exception while testing a case where the internet connection is interrupted:

`Unhandled rejection Error: getaddrinfo ENOTFOUND retsgw.flexmls.com retsgw.flexmls.com:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)`

There does not seem to be a way to catch this exception from outside of the RETS module. Is this something that can be caught and reported when calling 'getAutoLogoutClient'?

**Comment by jayrosen1576** [comment]
Ugh. Never mind. I didn't realize that 'getAutoLogoutClient' was also returning a promise. Solved my own issue.
