### ISSUE TITLE
RETS Server error while attempting search - HTTP Status 401 returned (RETS-Session-ID is invalid.)

### ISSUE THREAD

**Issue by rajeshdh** [sbruno81/rets-client#82]
I am trying to search for agents based on the rets listing but I am getting this error **RETS Server error while attempting search - HTTP Status 401 returned (RETS-Session-ID is invalid.)**

Here is my code
```
var rets = require('rets-client');
var fs = require('fs');

var config = require('./config');

var clientSettings = {
  loginUrl: config.settings.loginUrl,
  username: config.settings.username,
  password: config.settings.password,
  version: 'RETS/1.7.2',
  userAgent: config.settings.userAgent,
  method: 'POST' // tried 'GET' also 
};

// establish connection to RETS server which auto-logs out when we're done
rets.getAutoLogoutClient(clientSettings, function (client) {

  //perform a query using DMQL2 -- pass resource, class, and query, and options
  var lastImportTimeStamp = '2017-07-11T18:27:41';
  return client.search.query("Property", "RESI", "(Area=|10),(Status=|A,C,E,L,P,S,T,W,Y), (TransactionType=|S), (LastModifiedDateTime=" + lastImportTimeStamp + "+)", { limit: 10 })

    .then(function (searchData) {
      return searchData.results;
    })
    .then(function (results) {
      var getAgentData = function (x) {
        if (x < results.length) {
          return client.search.query('ActiveAgent', 'MEMB', '(MLSID=' + results[x].ListingAgentMLSID + ')')
            .then(function (agentData) {
              console.log(agentData);
              getAgentData(x + 1);
            }).catch(function (errorInfo) {
              var error = errorInfo.error || errorInfo;
              console.log("   ERROR: issue encountered:");
              outputFields(error);
              console.log('   ' + (error.stack || error).replace(/\n/g, '\n   '));
            });
        }
      };
      getAgentData(0);

    });
}).catch(function (errorInfo) {
  var error = errorInfo.error || errorInfo;
  console.log("   ERROR: issue encountered:");
  outputFields(error);
  console.log('   ' + (error.stack || error).replace(/\n/g, '\n   '));
});

```
And the output 

```
{ results: 
   [ { ContactPhoneAreaCode1: '760',
       ContactPhoneNumber1: '',
       ContactPhoneType1: 'Office',
       EmailAddress: '',
       FirstName: 'Diane',
       FullName: 'Diane Flores',
       IsActive: 'TRUE',
       LastName: 'Flores',
       LastModifiedDateTime: '2016-12-09T08:00:27',
       MemberNumber: '',
       MLSID: '17715',
       OfficeMLSID: '',
       OfficeName: 'Dee-Lux Realty, Inc.',
       OfficeNumber: '',
       PersonalFaxAreaCode: '',
       PersonalFaxPhone: '',
       PersonalFaxPhoneComplete: '',
       StreetAddress: '',
       WebPageAddress: '',
       ZipCode: '92311',
       ZipPlus4: '' } ],
  maxRowsExceeded: false,
  replyCode: '0',
  replyTag: 'OPERATION_SUCCESSFUL',
  replyText: 'Operation successful.',
  count: 1,
  rowsReceived: 1,
  headerInfo: undefined }
   ERROR: issue encountered:
      httpStatus: 401
      httpStatusMessage: "RETS-Session-ID is invalid."
      name: "RetsServerError"
      retsMethod: "search"
      queryOptions: {
        "QueryType": "DMQL2",
        "Format": "COMPACT-DECODED",
        "Count": 1,
        "StandardNames": 0,
        "RestrictedIndicator": "***",
        "Limit": "NONE",
        "SearchType": "ActiveAgent",
        "Class": "MEMB",
        "Query": "(MLSID=12804)"
      }
      headerInfo: {
        "server": "Microsoft-IIS/8.5",
        "xAspNetVersion": "2.0.50727",
        "wwwAuthenticate": "Digest realm=\"VIC\", nonce=\"7e6776683e76fed2e697143ac16e61e6\", opaque=\"8a68121ececdfd4741ef35096e4ada4e\", qop=\"auth\"",
        "vary": "Accept-Encoding",
        "cacheControl": "private",
        "contentType": "text/xml",
        "date": "Tue, 25 Jul 2017 17:02:36 GMT",
        "retsVersion": "RETS/1.7.2",
        "connection": "close",
        "xPoweredBy": "ASP.NET (204)"
      }
      message: "RETS Server error while attempting search - HTTP Status 401 returned (RETS-Session-ID is invalid.)"

   RetsServerError: RETS Server error while attempting search - HTTP Status 401 returned (RETS-Session-ID is invalid.)
       at Request.responseHandler (/home/superman/myProjects/retsSources/node_modules/rets-client/dist/utils/retsHttp.js:70:17)
       at emitOne (events.js:115:13)
       at Request.emit (events.js:210:7)
       at Request.onRequestResponse (/home/superman/myProjects/retsSources/node_modules/request/request.js:1074:10)
       at emitOne (events.js:115:13)
       at ClientRequest.emit (events.js:210:7)
       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
       at Socket.socketOnData (_http_client.js:453:20)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:252:12)
       at readableAddChunk (_stream_readable.js:239:11)
       at Socket.Readable.push (_stream_readable.js:197:10)
       at TCP.onread (net.js:588:20)
 
```

**Comment by esvinson** [comment]
It seems like when you call getAgentData(0); it's going to just return right after that, and end your session.

You might need to wrap that in a Promise, so it has time to process the agent queries before the logout happens.

Something like this (untested)

```
var rets = require('rets-client');
var fs = require('fs');

var config = require('./config');

var clientSettings = {
  loginUrl: config.settings.loginUrl,
  username: config.settings.username,
  password: config.settings.password,
  version: 'RETS/1.7.2',
  userAgent: config.settings.userAgent,
  method: 'POST' // tried 'GET' also 
};

// establish connection to RETS server which auto-logs out when we're done
rets.getAutoLogoutClient(clientSettings, function (client) {

  //perform a query using DMQL2 -- pass resource, class, and query, and options
  var lastImportTimeStamp = '2017-07-11T18:27:41';
  return client.search.query("Property", "RESI", "(Area=|10),(Status=|A,C,E,L,P,S,T,W,Y), (TransactionType=|S), (LastModifiedDateTime=" + lastImportTimeStamp + "+)", { limit: 10 })

    .then(function (searchData) {
      return searchData.results;
    })
    .then(function (results) {
      return new Promise(function(resolve, reject) {
        var getAgentData = function (x) {
          if (x < results.length) {
            return client.search.query('ActiveAgent', 'MEMB', '(MLSID=' + results[x].ListingAgentMLSID + ')')
              .then(function (agentData) {
                console.log(agentData);
                getAgentData(x + 1);
              }).catch(function (errorInfo) {
                var error = errorInfo.error || errorInfo;
                console.log("   ERROR: issue encountered:");
                outputFields(error);
                console.log('   ' + (error.stack || error).replace(/\n/g, '\n   '));
                reject(error);
              });
          } else {
            resolve(results);
          }
        };
        getAgentData(0);
      });
    });
}).catch(function (errorInfo) {
  var error = errorInfo.error || errorInfo;
  console.log("   ERROR: issue encountered:");
  outputFields(error);
  console.log('   ' + (error.stack || error).replace(/\n/g, '\n   '));
});
```
