### ISSUE TITLE
Issue running query

### ISSUE THREAD

**Issue by nmaves** [sbruno81/rets-client#83]
Here is the query 

```
let query = `(Matrix_Unique_ID=0+)&Select=Matrix_Unique_ID`
```

and here is the error

```
Unhandled rejection RetsReplyError: RETS Server reply while attempting search - ReplyCode 20206 (INVALID_QUERY_SYNTAX); ReplyText: DMQL: Syntax error - mismatched parenthesis
    at processStatus (/var/task/node_modules/rets-client/dist/utils/retsParsing.js:122:29)
    at Parser.<anonymous> (/var/task/node_modules/rets-client/dist/utils/retsParsing.js:135:7)
    at Parser.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser.parse (/var/task/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/var/task/node_modules/node-expat/lib/node-expat.js:60:19)
    at Request.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1088:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)

```

From the debug log I can see the uri below 

```
uri: 'http://matrixrets.recolorado.com/rets/Search.ashx?QueryType=DMQL2&Format=COMPACT-DECODED&Count=1&StandardNames=0&RestrictedIndicator=%2A%2A%2A&Limit=5000&Offset=1&SearchType=Property&Class=RESI&Query=%28Matrix_Unique_ID%3D0%2B%29%26Select%3DMatrix_Unique_ID'
```

I don't see the issue but the rets guys say that the query I have is valid.

**Comment by esvinson** [comment]
By adding the &Select to your query it's escaping the & to be %26 which is invalid, as it thinks that's part of the DMQL  query.
Your select fields should be passed in the 4th parameter to the search query.
`client.search.query('Resource', 'Class', '(Matrix_Unique_ID=0+)', {select: 'Matrix_Unique_Id'})`

**Comment by nmaves** [comment]
Wow, that worked like a charm.  We should really add that to the docs :)
