### ISSUE TITLE
20201 no records found causes crashes

### ISSUE THREAD

**Issue by Jscott388** [sbruno81/rets-client#94]
The no records found makes node crash. I don't want this happen and shouldn't crash when trying to fetch for updated records. 

RetsReplyError: RETS Server reply while attempting search - ReplyCode 20201 (NO_RECORDS_FOUND); ReplyText: No Records Found.
    at processStatus (/Users/joshuascott/Documents/web/RealEstateAWS/node_modules/rets-client/dist/utils/retsParsing.js:122:29)
    at Parser.<anonymous> (/Users/joshuascott/Documents/web/RealEstateAWS/node_modules/rets-client/dist/utils/retsParsing.js:162:20)
    at emitTwo (events.js:125:13)
    at Parser.emit (events.js:213:7)
    at Parser.parse (/Users/joshuascott/Documents/web/RealEstateAWS/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/Users/joshuascott/Documents/web/RealEstateAWS/node_modules/node-expat/lib/node-expat.js:60:19)
    at Request.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/joshuascott/Documents/web/RealEstateAWS/node_modules/request/request.js:1082:12)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at IncomingMessage.Readable.read (_stream_readable.js:464:10)
    at flow (_stream_readable.js:835:34)
    at resume_ (_stream_readable.js:817:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Jscott388** [comment]
Nevermind wrong method used
