### ISSUE TITLE
Getting 401 while trying to login using a proxy

### ISSUE THREAD

**Issue by rajeshdh** [sbruno81/rets-client#96]
I am trying to connect to one of the  Metrolist MLS systems that require me to log in using a proxy. 
I have specified proxy URL in the following format.
`http://username:password@myproxy.com:xxxx`
But I am not able to log into the system and getting 401 Unauthorized error.  

Note-: The proxy and MLS credentials were tested and working in ruby rets library.

**Comment by esvinson** [comment]
Try passing `useTunnel` as well.
```
{
proxyUrl: 'http://username:password@myproxy.com:xxxx',
useTunnel: true,
}
```

**Comment by rajeshdh** [comment]
It didn't work. I am getting
`Error: tunneling socket could not be established, statusCode=403`

**Comment by esvinson** [comment]
Do you have any debug output you could share?

We use this with a proxy (proximo.io plugin from Heroku) without any issues, but I think we had to use tunneling because it wasn't passing headers properly to generate the RETS Session ID.

**Comment by rajeshdh** [comment]
`DEBUG=* node index.js`  gives me 
```
rets-client:main RETS login: {} +0ms
  rets-client:request request: { debugId: 1,
  uri: myURL,
  method: 'GET',
  headers: 
   { 'User-Agent': 'xxxxxxxxxxx'
     'RETS-Version': 'RETS/1.7.2',
     'RETS-UA-Authorization': 'Digest 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
     host: 'x.x.x.x:0000' } } +19ms
  rets-client:main RETS login error: { Error: tunneling socket could not be established, statusCode=403
    at ClientRequest.onConnect (/home/myProjects/retsSources/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:320:30)
    at emitThree (events.js:135:13)
    at ClientRequest.emit (events.js:216:7)
    at Socket.socketOnData (_http_client.js:486:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
  cause: 
   { Error: tunneling socket could not be established, statusCode=403
       at ClientRequest.onConnect (/home/myProjects/retsSources/node_modules/tunnel-agent/index.js:166:19)
       at Object.onceWrapper (events.js:320:30)
       at emitThree (events.js:135:13)
       at ClientRequest.emit (events.js:216:7)
       at Socket.socketOnData (_http_client.js:486:11)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:266:12)
       at readableAddChunk (_stream_readable.js:253:11)
       at Socket.Readable.push (_stream_readable.js:211:10)
       at TCP.onread (net.js:585:20) code: 'ECONNRESET' },
  isOperational: true,
  code: 'ECONNRESET' } +1s
   ERROR: issue encountered:
      cause: {
        "code": "ECONNRESET"
      }
      code: "ECONNRESET"

   Error: tunneling socket could not be established, statusCode=403
       at ClientRequest.onConnect (/home/myProjects/retsSources/node_modules/tunnel-agent/index.js:166:19)
       at Object.onceWrapper (events.js:320:30)
       at emitThree (events.js:135:13)
       at ClientRequest.emit (events.js:216:7)
       at Socket.socketOnData (_http_client.js:486:11)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:266:12)
       at readableAddChunk (_stream_readable.js:253:11)
       at Socket.Readable.push (_stream_readable.js:211:10)
       at TCP.onread (net.js:585:20)

```

**Comment by esvinson** [comment]
How about the output when tunneling is disabled?

**Comment by rajeshdh** [comment]
Here it is
```
rets-client:main RETS login: {} +0ms
  rets-client:request request: { debugId: 1,
  uri: 'http://rets172.metrolist.net:6103/Metrolist/SACM/login.aspx',
  method: 'GET',
  headers: 
   { 'User-Agent': 'xxxxxxxxxxxxxx',
     'RETS-Version': 'RETS/1.7.2',
     'RETS-UA-Authorization': 'Digest 0xxxxxxxxxxxxxxxxxxxxxx',
     host: 'rets172.metrolist.net:6103',
     'proxy-authorization': 'Basic bWxzbGlzdGluZzpDSXNzMkZXZ2d0NWhtc0JET05XbTBwblFhekk3RGZCNVh2eTNvOUdsMVUxbUFpSkM1Mw==' } } +34ms
  rets-client:request auth: { debugId: 1,
  statusCode: 401,
  headers: 
   { date: 'Wed, 10 Jan 2018 16:05:19 GMT',
     server: 'Microsoft-IIS/6.0',
     'x-powered-by': 'ASP.NET (R02), ASP.NET',
     'x-aspnet-version': '2.0.50727',
     'www-authenticate': 'Digest realm="SACM", nonce="df5967343af6e50056cdb968c0177b73", opaque="0c9c44cd150c46c6132a1dbc9aca3539", qop="auth"',
     'rets-version': 'RETS/1.7.2',
     'cache-control': 'private',
     'content-type': 'text/xml',
     'x-cache': 'MISS from f4dacc0f72e3',
     'x-cache-lookup': 'MISS from f4dacc0f72e3:3128',
     via: '1.1 f4dacc0f72e3 (squid/3.3.8)',
     connection: 'close' },
  uri: 'http://rets172.metrolist.net:6103/Metrolist/SACM/login.aspx' } +1s
  rets-client:request request: { debugId: 1,
  uri: 'http://rets172.metrolist.net:6103/Metrolist/SACM/login.aspx',
  method: 'GET',
  headers: 
   { 'User-Agent': 'xxxxxxxxxxxxxxxxxx',
     'RETS-Version': 'RETS/1.7.2',
     'RETS-UA-Authorization': 'Digest 0xxxxxxxxxxxxxxxxxxxxxxxxxx',
     'proxy-authorization': 'Basic bWxzbGlzdGluZzpDSXNzMkZXZ2d0NWhtc0JET05XbTBwblFhekk3RGZCNVh2eTNvOUdsMVUxbUFpSkM1Mw==',
     authorization: 'Digest username="xxxxxxx", realm="SACM", nonce="df5967343af6e50056cdb968c0177b73", uri="http://rets172.metrolist.net:6103/Metrolist/SACM/login.aspx", qop=auth, response="a365964e32d7a2c8c1e5a40629df94f9", nc=00000001, cnonce="6d8bb349d38b4bc1b2cc49740d5c6b66", opaque="0c9c44cd150c46c6132a1dbc9aca3539"',
     referer: 'http://rets172.metrolist.net:6103/Metrolist/SACM/login.aspx',
     host: 'rets172.metrolist.net:6103' } } +2ms
  rets-client:request response: { debugId: 1,
  headers: 
   { date: 'Wed, 10 Jan 2018 16:05:21 GMT',
     server: 'Microsoft-IIS/6.0',
     'x-powered-by': 'ASP.NET (R02), ASP.NET',
     'x-aspnet-version': '2.0.50727',
     'www-authenticate': 'Digest realm="SACM", nonce="df5967343af6e50056cdb968c0177b73", opaque="0c9c44cd150c46c6132a1dbc9aca3539", qop="auth"',
     'rets-version': 'RETS/1.7.2',
     'cache-control': 'private',
     'content-type': 'text/xml',
     'x-cache': 'MISS from f3d6ea4d0dec',
     'x-cache-lookup': 'MISS from f3d6ea4d0dec:3128',
     via: '1.1 f3d6ea4d0dec (squid/3.3.8)',
     connection: 'close' },
  statusCode: 401,
  body: '' } +1s
  rets-client:main RETS login error: RETS Server error while attempting login - HTTP Status 401 returned (Unauthorized) +10ms
   ERROR: issue encountered:
      httpStatus: 401
      httpStatusMessage: "Unauthorized"
      name: "RetsServerError"
      retsMethod: "login"
      queryOptions: {}
      headerInfo: undefined
      message: "RETS Server error while attempting login - HTTP Status 401 returned (Unauthorized)"

   RetsServerError: RETS Server error while attempting login - HTTP Status 401 returned (Unauthorized)
       at /home/myProjects/retsSources/node_modules/rets-client/dist/utils/retsHttp.js:39:17
       at tryCatcher (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/util.js:26:23)
       at Promise._settlePromiseFromHandler (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:508:31)
       at Promise._settlePromiseAt (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:584:18)
       at Promise._settlePromises (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/promise.js:700:14)
       at Async._drainQueue (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/async.js:123:16)
       at Async._drainQueues (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues (/home/myProjects/retsSources/node_modules/rets-client/node_modules/bluebird/js/main/async.js:15:14)
       at runCallback (timers.js:781:20)
       at tryOnImmediate (timers.js:743:5)
       at processImmediate [as _immediateCallback] (timers.js:714:5)

```

**Comment by esvinson** [comment]
You'll want to strip out/obfuscate the value in the `proxy-authorization` from your comment above (base64 credentials).

I think this might be the same issue we were seeing, where the server validates the Digest auth based on the relative URL but the request library generates the digest based on the Full URL because it has to send it through the proxy. (https://github.com/request/request/blob/v2.83.1/request.js#L399)

https://github.com/request/request/blob/master/lib/auth.js#L50

https://github.com/request/request/blob/master/request.js#L392-L400

**Comment by esvinson** [comment]
Enabling tunneling worked for us because it skips this:
https://github.com/request/request/blob/v2.83.1/request.js#L398-L400
```
  if (self.proxy && !self.tunnel) {
    self.path = (self.uri.protocol + '//' + self.uri.host + self.path)
  }
```

**Comment by esvinson** [comment]
I have a fix for this:  (Verified locally using the same Sacramento Metrolist feed (our credentials))
https://github.com/esvinson/request/tree/bugfix/proxy-url-fix
https://github.com/esvinson/request/commit/b92f08e238eccf842f46cb6d10fdb82911e8e260

I won't have time today to build out the necessary tests for them to approve getting this merged though.

**Comment by rajeshdh** [comment]
This worked for me. Thanks a ton.
